import 'package:flutter/material.dart';

class AboutScreen extends StatefulWidget {
  @override
  _AboutScreenState createState() => _AboutScreenState();
}

class _AboutScreenState extends State<AboutScreen> {
  String _aboutTasteMore =
      '''  Taste More is an app that allows anonymous feedback on restaurants.
   
  Provide your feedback on portion size/food quality/anything under the sun! 
  
  Also, we hope to increase the efforts towards reducing food waste and going green while dining!
''';

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          backgroundColor: Colors.green,
          title: new Text("Taste More, Waste Less!"),
          centerTitle: true,
          actions: <Widget>[
            IconButton(
                icon: Icon(
                  Icons.help,
                  color: Colors.greenAccent,
                  size: 35.0,
                ),
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => DidYouKnow()),
                  );
                }),
//
          ],
        ),
        body: new Stack(
          children: <Widget>[
            Center(
              child: new Image.asset(
                'assets/background_notes.jpg',
                width: 490.0,
                height: 1200.0,
                fit: BoxFit.fill,
              ),
            ),
            ListTile(
              subtitle: Align(
                child: Text(
                  _aboutTasteMore,
                  style: TextStyle(color: Colors.black, fontSize: 19.0),
                ),
                alignment: Alignment(1, -1),
              ),
            ),
          ],
        ));
  }
}

class DidYouKnow extends StatelessWidget {
  String _didYouKnowInfo =
      '''More than half of food waste generated by Singapore households would not have been trashed if they were better managed, such as by buying and cooking the right proportions, a waste audit has found.

This amount of "avoidable" food waste generated by each household amounts to chucking a 2.5kg bag of rice each week, according to the National Environment Agency (NEA).
''';

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        appBar: new AppBar(
          title: new Text("Did You Know?"),
          centerTitle: true,
          backgroundColor: Colors.green,
        ),
        body: new Stack(
          children: <Widget>[
            Center(
              child: new Image.asset(
                'assets/background_leaf.jpg',
                width: 490.0,
                height: 1200.0,
                fit: BoxFit.fill,
              ),
            ),
            new ListView(
              children: <Widget>[
                new ListTile(
                  subtitle: new Text(
                    _didYouKnowInfo,
                    style: TextStyle(color: Colors.black, fontSize: 19.0),
                  ),
                )
              ],
            ),
          ],
        ));
  }
}
